apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: l3
  namespace: location
  annotations:
    service/owner: "a8u.han1fa@gmail.com"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 2
  template:
    metadata:
      labels:
        app: l3
    spec:
      containers:
        - name: l3-webserver
          image: a8uhnf/l3:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
